# Generated by Django 5.0.1 on 2024-01-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("carbs", models.FloatField()),
                ("protein", models.FloatField()),
                ("fat", models.FloatField()),
                ("calories", models.FloatField()),
            ],
        ),
    ]
