# Generated by Django 5.0.1 on 2024-01-21 08:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_consumption"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Consumption",
            new_name="Consume",
        ),
    ]
